### ISSUE TITLE
Add HOC connector for react class components

### ISSUE THREAD

**Issue by mikhailKilin** [artalar/reatom#143]
Hi! I have an idea how to implement this feature. I would like to discuss it.

**Comment by belozer** [comment]
@mikhailKilin thanks! Go to t.me/reatom_ru

**Comment by noveogroup-amorgunov** [comment]
@belozer Hi! Do you have any plans to implement this feature?

**Comment by artalar** [comment]
So old issue :)

Hi there! I closing this issue as outdated, coz nobody ping it long time.

By the way, as an solution you always may write simple HOC by the hooks reuse:

```ts
const withReatom = (Component, atoms) => {
  const combinedAtom = combine(atoms);
  return (props) => <Component {...props} {...useAtom(combinedAtom)} />;
};
// ...
const Counter = withReatom(CounterRaw, { value: counterAtom })
```

We will not to add it to the package, because an HOC may require a lot of other options, like actionCreators bindings, custom memoization, on mount selector creation and so on. It is hard to maintain but seems not demand (this issue is silent for more than one year).
Also, I want to repeat it, you may create HOC with any options by hooks.
