### ISSUE TITLE
Add "svelte" package

### ISSUE THREAD

**Issue by artalar** [artalar/reatom#16]
[React package](https://github.com/artalar/reatom/tree/master/packages/react) may be used as a template

**Comment by Kurzdor** [comment]
bindings on codesandbox
https://codesandbox.io/s/strange-shape-qvdby

**Comment by resolritter** [comment]
Hi! I've noticed the provided sandbox link is broken, although the code looks fine. The code transpilation code might be wrong. On a similar note, I was not able to use the core `observe` method for some reason. It might have to do with how the packaged code is transpiling the `Observable` class and it could be related to this error as well.

I've attempted to fix it in this sandbox:  https://codesandbox.io/s/reatom-svelte-jhlho?file=/StoreObservable.js. StoreObservable is the class which I had to provide due to the problems I explained above.

As noted in the code comment, Svelte needs the listener to be called once at the start of the subscription; otherwise, the value starts as undefined in the view.

**Comment by artalar** [comment]
@resolritter looks good! Do you want to make a PR with new package?

**Comment by resolritter** [comment]
@artalar I can. If you wouldn't mind answering those two questions:

1. Isn't it problematic that the `observe` method from `@reatom/core` didn't work? The exception in that bugged sandbox (https://codesandbox.io/s/musing-banach-sg125) says "store.subscribe is not a function"; I've logged and seen that the `subscribe` method indeed exists, but for some reason it isn't accessible through svelte. I think it is a better idea to look on what's wrong there instead of relying on this custom StoreObservable class (which might become outdated in relation to the `@reatom/core` API).
2. Which "wrapper" methods do you have in mind? For example
- `bindAction` https://codesandbox.io/s/musing-banach-sg125?file=/svelte-binding.js
- `observeAtom` https://codesandbox.io/s/musing-banach-sg125?file=/svelte-binding.js

I have never worked with Svelte, so that's why I'm asking what functions could be useful. I'll read up more of the documentation and try to come up with suggestions for the package's API. Thanks!

**Comment by artalar** [comment]
@resolritter 
1. Im 90+% sure thats is the Codesandbox transpiler bug (try to download sources and start it locally with fresh dependencies)
2. @PaulMaly can u recommending some good naming conventions for svelte ecosystem? + review the proposed API plz

**Comment by resolritter** [comment]
I've prototyped one API called `derive`

https://svelte.dev/docs#derived

This is similar to the `map` function in this library, but it does a few more things.

I think the other methods listed in https://svelte.dev/docs#svelte_store are already feasible without needing any wrappers.
