### ISSUE TITLE
useAction not working on Next.js app

### ISSUE THREAD

**Issue by alinurr1** [artalar/reatom#364]
Hello! 

I have walked through the sandbox code that was provided in one of the issues: https://codesandbox.io/s/reatom-example-285-15s7o?file=/src/App.tsx

I've declared atoms and actions the same way as was described in the above-mentioned sandbox.
Since I am using Next.js I don't have a usual App.js file, rather I have _app.tsx file in the page directory, for which I also provided context from createStore():

```
<context.Provider value={store}>
  <ApolloProvider client={apollo}>
    <Component {...pageProps} />
  </ApolloProvider>
</context.Provider>
```

The issue arises when I try to call a function that was given from useAction hook. The function does not seem to modify the state at all, rather the default value that was provided to the atom remains in the state.

Thanks in advance for any kind of help or guidance on this problem :)

**Comment by artalar** [comment]
Hi, first of all check version of the reatom/react package, it should be `1.1.5` (published 2 months ago).
If you install the last version and the bug is still reproduce, try to add / remove `<React.StrictMode>` in the root of your app and check the behavior.
Otherwise try to reproduce the bug in the codesandbox and attach the link, please.

**Comment by artalar** [comment]
@alinurr1 is it help?

**Comment by artalar** [comment]
Probably, outdated
