### ISSUE TITLE
[BUG] Issues in combination Sveltekit 

### ISSUE THREAD

**Issue by mindreframer** [artalar/reatom#573]
Hey @artalar , thanks for this cool library! 

I would like to try it in combination with Svelte. For testing I started using it with sveltekit scaffold and it complaints when I try to render it. 

There seems to be an issue with "@reatom/framework" re-exports... 

```
Internal server error: Unexpected token 'export'
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1176:20)
      at Module._compile (node:internal/modules/cjs/loader:1218:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:958:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:194:25) (x14)
reatom/node_modules/.pnpm/@reatom+framework@3.4.6/node_modules/@reatom/framework/build/index.module.js:1
export*from"@reatom/async";export*from"@reatom/core";export*from"@reatom/effects";export*from"@reatom/hooks";export*from"@reatom/lens";export*from"@reatom/logger";export*from"@reatom/primitives";export*from"@reatom/utils";
```

Repo with reproduction: 

- https://github.com/mindreframer/reatom-sveltekit-issue/
- https://github.com/mindreframer/reatom-sveltekit-issue/blob/main/error-message.png

Is this a known issue? Some configuration settings to fix it? 

Thanks!

**Comment by mindreframer** [comment]
In an another, plain Svelte project the importing / bundling works fine...

**Comment by mindreframer** [comment]
Example in a sandbox REPL here: 

- https://www.sveltelab.dev/lpyf3ohs6ynu008

**Comment by artalar** [comment]
Douno. Did you use the last version of vite, the kit and so on?

**Comment by artalar** [comment]
Here is the same issue https://github.com/sveltejs/kit/issues/7363

**Comment by artalar** [comment]
@mindreframer try `npm-svelte@3.1.2` plese

**Comment by mindreframer** [comment]
Hmm... On NPM I see only 3.1.0... 
<img width="521" alt="Screenshot 2023-07-08 at 14 13 36" src="https://github.com/artalar/reatom/assets/1232/891357f3-5c35-4119-860d-72318f2306a8">


Also, here is the repo - https://github.com/mindreframer/reatom-sveltekit-issue. Update did not change the error message locally

**Comment by nightire** [comment]
I think reatom is currently not compatible with vite@5, because it now only support esm packages.

EDIT: with a bit of digging in, I can confirm the compatible issue and it is relatively easy to fix on reatom side. Just add `"type": "module"` in package.json of all published packages. cc @artalar

**Comment by BANOnotIT** [comment]
@nightire But how `"type": "module"` can help? All packages already have `"exports"` with "default" conditions and `"module": "./some.js"`.  Can you provide any link on what exactly `"type": "module"` will change?

**Comment by nightire** [comment]
@BANOnotIT I don't know what changed behind the scenes; I just have tried everything to make vite@5 work.

It's easy to try yourself: bootstrap a vite@5 project, install Reatom, and run it to see the error. Then, overwrite the package.json files in the `node_modules` folder, and everything works well.

EDIT:
Here's my speculation, according to the official document: https://nodejs.org/api/packages.html#type

<img width="980" alt="image" src="https://github.com/artalar/reatom/assets/1104018/93d388be-b545-4055-b817-bbcba94bd9d8">

Because of the exports field, modules belonging to Reatom should be fine. However, third-party modules directly dependent on reatom still need the `"type": "module"` field; otherwise, they will be parsed as CommonJS modules and cause problems with Vite@5.

Again, that's my best guess, but it did works for me.

**Comment by artalar** [comment]
The changes from the PR is finally published, please, recheck your problem <3
