### ISSUE TITLE
reatom/core-v1 Module not found: Error: Default condition should be last one

### ISSUE THREAD

**Issue by ArSharlahy** [artalar/reatom#587]
после перехода на версию 3.1.5, на большинстве экшенов начала вылезать ошибка Module not found: Error: Default condition should be last one, при откате  на 3.1.4 проблема уходит

**Comment by BANOnotIT** [comment]
Would you mind giving info about the bundler you're using?

**Comment by BANOnotIT** [comment]
As far as I see the problem is the order of keys in "exports" fields in package.json. This was an massive refactor in [this commit](https://github.com/artalar/reatom/commit/99550e98c34df7efd8431282a868a0483bed5dc8).

I think there might be some package.json validator out there? Since there are new rules for package overrides, exports semantics, and might be some other things and as we have many packages it might be breaking for us.

**Comment by BANOnotIT** [comment]
@JulianCataldo hello! Can I ask you to fix this issue by adding the "default" conditional export as last property in exports and "types" as first? The order of keys in "exports" has semantics and the doc [specifically states default](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#conditional-exports) should be the last one. Also typescript [defines that "types" should always be first](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing) in "exports".

P.S. yeah, let's give semantics to previously unordered maps and behave like everyone would understand that! Isn't that a great idea, OpenJS foundation?

**Comment by artalar** [comment]
done
