### ISSUE TITLE
Use Babel for auto generate atom name from variable name

### ISSUE THREAD

**Issue by Akiyamka** [artalar/reatom#625]
For better logs we need to pass atom name to the `atom` function, like
```js
const foo = atom(0, 'foo');
const bar = atom('some value', 'bar');
const baz = atom([], 'baz');
```
This is pretty dumb copy-paste moment that would be better generated automatically.
Would be cool to create an babel plugin that do it

**Comment by artalar** [comment]
We thought a lot about this, and decided that adding babel creates more problems than it solves:

 • Build tooling varies, aside from the outdated Babel, there are a bunch of other tools written in different languages, it's difficult to maintain all of this;
 • The result of the plugin's work is not visible and can lead to unpleasant debugging;
 • Transpilation tools and plugins often catch certain errors, including due to JavaScript's complexity as a language, and the ecosystem's disconnectedness;
 • It's hard to cover all cases with a single transpilation, factories cause the most problems;
 • The name contains a hash - redundant information during debugging;
 • The hash is tied to a file and line - it can easily change with the slightest refactoring, causing user cache to drop, this should be taken into account in automatic migrations (talking about client persist state).
I didn't come up with this myself, there was a plugin for the first reatom and it was clear then that the game isn't worth the candle, the situation is even worse now.

On the contrary, manually writing the name in an argument carries a bunch of advantages:
 • Absolutely clear;
 • Full control;
 • Zero set up, not difficult, really not difficult, in terms of code quantity and complexity, required efforts - it's nothing;
 • Co-pilot even handles it for meyou can use an eslint plugin with autofix now (https://www.reatom.dev/package/eslint-plugin/).
